trigger:
  branches:
    include:
    - master
  tags:
    include:
    - v*

variables:
  buildConfiguration: 'Release'
  isGitHubTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/v')]

stages:
- stage: Build
  jobs:
  - job: Test_Build
    condition: ne(variables['isGitHubTag'], 'true')
    pool:
      vmImage: 'windows-2019'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'update -g dotnet-format'
      displayName: 'Install .NET Core format tool'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '-c $(buildConfiguration)'
      displayName: 'Build for test'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'format'
        arguments: '--dry-run --check --verbosity diagnostic'
      displayName: 'Lint C# code'

  - job: Build_NuPkg
    condition: eq(variables['isGitHubTag'], 'true')
    pool:
      vmImage: 'windows-2019'
    steps:
    - powershell: 'echo "##vso[task.setvariable variable=PackageVersion]$($env:Build_SourceBranchName.Substring(1))"'
      displayName: 'PowerShell Script'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet pack'
      inputs:
        command: pack
        packagesToPack: '**/Sharprompt.csproj'
        packDirectory: '$(Build.SourcesDirectory)/dist'
        versioningScheme: byEnvVar
        versionEnvVar: PackageVersion
        verbosityPack: Normal

    - publish: dist
      artifact: nupkg
      displayName: 'Publish artifacts'

- stage: Publish
  dependsOn:
  - Build
  condition: and(succeeded(), eq(variables['isGitHubTag'], 'true'))
  jobs:
  - job: Publish_Nupkg
    pool:
      vmImage: 'windows-2019'
    steps:
    - checkout: none

    - download: current
      artifact: nupkg
      displayName: 'Download artifact'

    - task: NuGetCommand@2
      displayName: 'Push nupkg'
      inputs:
        command: push
        packagesToPush: '$(Pipeline.Workspace)/**/*.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: NuGet
        verbosityPush: Normal