//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharprompt.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharprompt.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmForm_Answer_No {
            get {
                return ResourceManager.GetString("ConfirmForm_Answer_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmForm_Answer_Yes {
            get {
                return ResourceManager.GetString("ConfirmForm_Answer_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sharprompt requires an interactive environment. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_NotSupportedEnvironment {
            get {
                return ResourceManager.GetString("Message_NotSupportedEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ({0} items, {1}/{2} pages) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_Pagination {
            get {
                return ResourceManager.GetString("Message_Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The prompt was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Message_PromptCanceled {
            get {
                return ResourceManager.GetString("Message_PromptCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hit &lt;space&gt; to select, &lt;ctrl+a&gt; to toggle all, &lt;ctrl+i&gt; to invert selection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MultiSelectForm_Message_Hint {
            get {
                return ResourceManager.GetString("MultiSelectForm_Message_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is invalid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Invalid {
            get {
                return ResourceManager.GetString("Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A maximum input of {0} items is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Maximum_InputRequired {
            get {
                return ResourceManager.GetString("Validation_Maximum_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum ({0}) is not valid when minimum is set to ({1}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Maximum_OutOfRange {
            get {
                return ResourceManager.GetString("Validation_Maximum_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A maximum selection of {0} items is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Maximum_SelectionRequired {
            get {
                return ResourceManager.GetString("Validation_Maximum_SelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too long に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A minimum input of {0} items is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Minimum_InputRequired {
            get {
                return ResourceManager.GetString("Validation_Minimum_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The minimum ({0}) is not valid に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Minimum_OutOfRange {
            get {
                return ResourceManager.GetString("Validation_Minimum_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A minimum selection of {0} items is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Minimum_SelectionRequired {
            get {
                return ResourceManager.GetString("Validation_Minimum_SelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is too short に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is not match pattern に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_RegularExpression {
            get {
                return ResourceManager.GetString("Validation_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value is required に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} is incompatible type with {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Type_Incompatible {
            get {
                return ResourceManager.GetString("Validation_Type_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} type does not have a {1} member に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Type_MemberNotFound {
            get {
                return ResourceManager.GetString("Validation_Type_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot specify a method with arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Validation_Type_NotParameterlessMethod {
            get {
                return ResourceManager.GetString("Validation_Type_NotParameterlessMethod", resourceCulture);
            }
        }
    }
}
