using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Sharprompt.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class EnumMetadataGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat s_fullyQualifiedFormat = SymbolDisplayFormat.FullyQualifiedFormat;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (syntaxContext, cancellationToken) => (INamedTypeSymbol?)syntaxContext.SemanticModel.GetDeclaredSymbol((EnumDeclarationSyntax)syntaxContext.Node, cancellationToken))
            .Where(static symbol => symbol is not null);

        context.RegisterSourceOutput(provider, static (productionContext, symbol) =>
        {
            var enumSymbol = symbol!;
            var source = GenerateSource(enumSymbol);
            if (source.Length == 0)
            {
                return;
            }

            var hintName = enumSymbol.ToDisplayString()
                .Replace('<', '_')
                .Replace('>', '_')
                .Replace(',', '_')
                .Replace(' ', '_')
                .Replace('.', '_')
                + ".EnumMetadata.g.cs";

            productionContext.AddSource(hintName, source);
        });
    }

    private static string GenerateSource(INamedTypeSymbol enumSymbol)
    {
        var members = enumSymbol.GetMembers()
            .OfType<IFieldSymbol>()
            .Where(field => field.HasConstantValue)
            .Select((field, index) => AnalyzeMember(enumSymbol, field, index))
            .ToArray();

        if (members.Length == 0)
        {
            return string.Empty;
        }

        var orderedMembers = members
            .OrderBy(member => member.Order ?? int.MaxValue)
            .ThenBy(member => member.Index)
            .ToArray();

        var enumTypeName = enumSymbol.ToDisplayString(s_fullyQualifiedFormat);
        var typeIdentifier = Sanitize(enumSymbol.ToDisplayString());

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("file static class __SharpromptEnumMetadata_" + typeIdentifier);
        builder.AppendLine("{");
        builder.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        builder.AppendLine("    internal static void Register()");
        builder.AppendLine("    {");
        builder.AppendLine("        global::Sharprompt.EnumMetadataRegistry.Register<" + enumTypeName + ">(");
        builder.AppendLine("            new " + enumTypeName + "[]");
        builder.AppendLine("            {");

        for (var i = 0; i < orderedMembers.Length; i++)
        {
            var suffix = i == orderedMembers.Length - 1 ? string.Empty : ",";
            builder.AppendLine("                " + enumTypeName + "." + orderedMembers[i].Name + suffix);
        }

        builder.AppendLine("            },");
        builder.AppendLine("            value => value switch");
        builder.AppendLine("            {");

        foreach (var member in members)
        {
            builder.AppendLine("                " + enumTypeName + "." + member.Name + " => " + Quote(member.DisplayName) + ",");
        }

        builder.AppendLine("                _ => value.ToString()");
        builder.AppendLine("            });");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    private static EnumMemberMetadata AnalyzeMember(INamedTypeSymbol enumSymbol, IFieldSymbol field, int index)
    {
        var displayName = field.Name;
        int? order = null;

        var displayAttribute = field.GetAttributes()
            .FirstOrDefault(attribute => attribute.AttributeClass?.ToDisplayString() == "System.ComponentModel.DataAnnotations.DisplayAttribute");

        if (displayAttribute != null)
        {
            foreach (var namedArgument in displayAttribute.NamedArguments)
            {
                if (namedArgument.Key == "Name" && namedArgument.Value.Value is string name)
                {
                    displayName = name;
                }
                else if (namedArgument.Key == "Order" && namedArgument.Value.Value is int value)
                {
                    order = value;
                }
            }
        }

        return new EnumMemberMetadata(field.Name, displayName, order, index);
    }

    private static string Quote(string text)
    {
        return "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r") + "\"";
    }

    private static string Sanitize(string name)
    {
        var builder = new StringBuilder(name.Length);

        foreach (var c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }

        return builder.ToString();
    }

    private sealed class EnumMemberMetadata
    {
        public EnumMemberMetadata(string name, string displayName, int? order, int index)
        {
            Name = name;
            DisplayName = displayName;
            Order = order;
            Index = index;
        }

        public string Name { get; }
        public string DisplayName { get; }
        public int? Order { get; }
        public int Index { get; }
    }
}
