name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - '.github/workflows/docs.yml'
      - '.github/workflows/publish.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'
      - '.github/workflows/docs.yml'
      - '.github/workflows/publish.yml'

permissions:
  contents: read

env:
  DOTNET_VERSION: 8.0.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Use .NET ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build project
      run: dotnet build -c Release

    - name: Run test cases
      run: dotnet test -c Release --no-build

    - name: Lint C# code
      run: dotnet format --verify-no-changes --verbosity detailed --no-restore
